const express = require('express');
const route = express.Router();
const ChiNhanhController = require('../controllers/ChiNhanhController');
const {authMiddleware} = require('../middleware/authMiddleware');
const {authorizeRoles} = require('../middleware/authMiddleware');
route.get('/',authMiddleware,ChiNhanhController.getAll);
route.post('/',authorizeRoles(1,3), ChiNhanhController.create);
route.put('/:MaCN',authorizeRoles(1,3), ChiNhanhController.update);
route.delete('/:MaCN',authorizeRoles(1,3), ChiNhanhController.delete);
module.exports = route;