const express = require('express');
const route = express.Router();
const NguoiPhuThuocController = require("../controllers/NguoiPhuThuocController");
const { authMiddleware } = require("../middleware/authMiddleware");
const { authorizeRoles } = require("../middleware/authMiddleware");
route.get("/:MaTK",authMiddleware, NguoiPhuThuocController.getByNV);
route.post("/",authMiddleware, authorizeRoles(1,3) ,NguoiPhuThuocController.create);
route.put("/:MaNPT",authMiddleware, authorizeRoles(1,3),NguoiPhuThuocController.update);
route.delete("/:MaNPT",authMiddleware, authorizeRoles(1,3),NguoiPhuThuocController.delete);
module.exports = route;