const express = require('express');
const route = express.Router();
const TaiKhoanController = require("../controllers/TaiKhoanController");
const {uploadAvatar} = require("../middleware/upload");
route.get('/',TaiKhoanController.getAll);
route.get('/getAllNhanVien',TaiKhoanController.getAllNhanVien);
route.get('/:MaTK',TaiKhoanController.getById);
route.post('/',uploadAvatar.single('avatar'),TaiKhoanController.create);
route.put('/:MaTK',uploadAvatar.single('avatar'),TaiKhoanController.update);
module.exports = route;