export const employeeData = [{
  id: 1,
  code: "NV000003",
  timekeepingCode: "",
  name: "Nhân viên 11",
  phone: "45",
  idNumber: "",
  debt: "0",
  notes: "",
  avatar: null,
  email: "employee11@example.com",
  birthDate: "01/01/1990",
  gender: "Nam",
  address: "Hà Nội, Việt Nam",
  department: "IT",
  position: "Developer",
  startDate: "01/01/2022",
  payrollBranch: "Chi nhánh trung tâm",
  kiotVietAccount: "kiotviet_user1",
  facebook: "facebook.com/user1",
  mobileDevice: "iPhone 13"
}, {
  id: 2,
  code: "NV000002",
  timekeepingCode: "",
  name: "Nhân viên 1",
  phone: "113",
  idNumber: "",
  debt: "0",
  notes: "",
  avatar: null,
  email: "employee1@example.com",
  birthDate: "15/05/1992",
  gender: "Nữ",
  address: "TP. Hồ Chí Minh, Việt Nam",
  department: "Marketing",
  position: "Marketing Manager",
  startDate: "15/06/2021",
  payrollBranch: "Chi nhánh 2",
  kiotVietAccount: "kiotviet_user2",
  facebook: "facebook.com/user2",
  mobileDevice: "Samsung Galaxy S21"
}];